### ISSUE TITLE
Bungee 1.15

### ISSUE THREAD

**Issue by ManO1234148** [kangarko/PunishControl#3]
I want the plugin to load but it gives me a strange error

https://pastebin.com/G5YwjSDx

**Comment by JavaFactoryDev** [comment]
Hi Man01234148,

thank you for reporting this, will be fixed in the next release.

Regards,
Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Issue resolved with the latest version.

**Comment by ManO1234148** [comment]
Issue is not fixed, i updated to latest and am still getting issues

**Comment by ManO1234148** [comment]
https://ghostbin.co/paste/fwsds

**Comment by JavaFactoryDev** [comment]
Hi,

this is a different issue and its not related to PunishControl: "OutOfMemoryError: Java heap space"
Please just add enough RAM to your BungeeCord server

Regards,
Leonhard from MineAcademy
